### PR TITLE
fix to_string() implementation

### PR DESCRIPTION
**Pull request by aldebaranzbradaradjan**
fix this issue : https://github.com/return/branca/issues/14

### CODE REVIEW

**Review by brycx — COMMENTED** [review]
I would suggest implementing `AsRef<str> for BrancaError`, such that the `description()` method can return something useful, instead of `"branca error, see to_string() for details"`. I imagine it would look something like so:

```rust
impl AsRef<str> for Error {
    fn as_ref(&self) -> &str {
        match *self {
            Error::InvalidBase62Token => "Base62 token is invalid.",
            Error::InvalidTokenVersion => "Token version is invalid.",
            Error::BadNonceLength => "Bad nonce length.",
            Error::BadKeyLength => "Bad key length.",
            Error::ExpiredToken => "This token has expired.",
            Error::DecryptFailed => "Decryption failed.",
            Error::EncryptFailed => "Encryption failed.",
        }
    }
}
```
and then calling `as_ref()` in the needed methods:

```rust
impl fmt::Display for Error {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        write!(fmt, "{}", self.as_ref())
    }
}

impl StdErr for Error {
    fn description(&self) -> &str {
        self.as_ref()
    }
}
```
@aldebaranzbradaradjan does this also solve your issue (there's also the approach I mentioned in #14)? Maybe also wait for @return to see what they think about this.

**Comment by aldebaranzbradaradjan** [comment]
Cool, compared to what you showed on my issue, couldn't we do Display implementation like that in AsRef ? Like this:
```rust
impl AsRef <str> for Error {
     fn as_ref (& self) -> & str {
         format! ("{:?}", self)
     }
}

impl fmt :: Display for Error {
     fn fmt (& self, fmt: & mut fmt :: Formatter) -> fmt :: Result {
         write! (fmt, "{}", self.as_ref ())
     }
}

impl StdErr for Error {
     fn description (& self) -> & str {
         self.as_ref ()
     }
}
```

Or even like that? :
```rust
impl fmt :: Display for Error {
     fn fmt (& self, fmt: & mut fmt :: Formatter) -> fmt :: Result {
         write! (fmt, "{:?}", self)
     }
}

impl StdErr for Error {
     fn description (& self) -> & str {
         format! ("{:?}", self)
     }
}
```
It's shorter and it avoids storing the strings of errors, I like it :)
After we wait for Return to see what he thinks, it seems good to me.
I had never done a PR I don't know how it goes.

The test is good I think!

**Comment by brycx** [comment]
I have spoken with @return and they're currently very busy. I believe the best action now is to fix the issue with as little modification to the current model as possible. Then @return can revisit once possible, and see if another approach should be taken. Right now, we need to fix this overflow. @aldebaranzbradaradjan if you could change the `Display` impl to use the `Debug` impl and add the test, then I can merge the fix (let's keep the `description` as-is). 

```rust
impl fmt::Display for Error {
    fn fmt(&self, fmt: &mut fmt::Formatter) -> fmt::Result {
        write!(fmt, "{:?}", self)
    }
}
```

**Comment by aldebaranzbradaradjan** [comment]
Ok, will do that.

**Comment by brycx** [comment]
Sorry, I was unclear about `description()`. I meant it should be reverted to original, I've fixed it in https://github.com/return/branca/pull/15/commits/7e1eed386b075edb6c016d27128e43ab91b84dda.

Thank you for taking the time to fix this issue @aldebaranzbradaradjan!

**Pull request merged**
